Revert "Introduce wisp-client (cashapp/misk#1826)" (cashapp/misk#1827)
This reverts commit d7f610fcbdabb8ac3242899696be3213477f0a5c for breaking downstream
consumers due to injection failure:

```
    java.lang.NoClassDefFoundError: misk/client/EnvoyClientEndpointProvider
```