Add ExecutorServiceFactory wrapper for transacter with reader qualifier
Vitess transacter expect to have one executer per shard, and resue the
thread factory for the reader qualifier causes the following exception:

```
java.lang.IllegalStateException: multiple executor services named shard-list-fetcher-%d - this could be a thread leak!
```

The wrapper adds the `reader-` prefix to executers created by
RealTransacter.