Revert "Introduce wisp-client (#1826)" (#1827)
This reverts commit fb4907d5c27ea9e322006c4566700702b3fca838 for breaking downstream
consumers due to injection failure:

```
    java.lang.NoClassDefFoundError: misk/client/EnvoyClientEndpointProvider
```