fix: make MiskOpaMetrics a singleton. This was causing issues like (#2950)
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: Failed to register Collector of type Counter: opa_server_query_cache_hit_total is already in use by another Collector of type Counter

at MiskOpaMetrics.<init>(MiskOpaMetrics.kt:12)