This PR contains the following updates:
| Package | Type | Package file | Manager | Update | Change |
|---|---|---|---|---|---|
| [app.cash.tempest:tempest-bom](https://github.com/cashapp/tempest) |
dependencies | misk/gradle/libs.versions.toml | gradle | minor |
`2025.05.02.195945-d393c44` -> `2025.06.03.162437-8f485e7` |
| [io.lettuce:lettuce-core](https://github.com/redis/lettuce) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`6.7.0.RELEASE` -> `6.7.1.RELEASE` |
|
[com.google.apis:google-api-services-cloudkms](http://nexus.sonatype.org/oss-repository-hosting.html)
([source](http://svn.sonatype.org/spice/tags/oss-parent-7)) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`v1-rev20250516-2.0.0` -> `v1-rev20250523-2.0.0` |
|
[org.bouncycastle:bcprov-jdk18on](https://www.bouncycastle.org/download/bouncy-castle-java/)
([source](https://github.com/bcgit/bc-java)) | dependencies |
misk/gradle/libs.versions.toml | gradle | minor | `1.80` -> `1.81` |
|
[org.bouncycastle:bcpkix-jdk18on](https://www.bouncycastle.org/download/bouncy-castle-java/)
([source](https://github.com/bcgit/bc-java)) | dependencies |
misk/gradle/libs.versions.toml | gradle | minor | `1.80` -> `1.81` |
|
[org.bouncycastle:bcpg-jdk18on](https://www.bouncycastle.org/download/bouncy-castle-java/)
([source](https://github.com/bcgit/bc-java)) | dependencies |
misk/gradle/libs.versions.toml | gradle | minor | `1.80` -> `1.81` |
| [software.amazon.awssdk:sdk-core](https://aws.amazon.com/sdkforjava) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`2.31.55` -> `2.31.56` |
| [software.amazon.awssdk:sqs](https://aws.amazon.com/sdkforjava) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`2.31.55` -> `2.31.56` |
|
[software.amazon.awssdk:dynamodb-enhanced](https://aws.amazon.com/sdkforjava)
| dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`2.31.55` -> `2.31.56` |
| [software.amazon.awssdk:dynamodb](https://aws.amazon.com/sdkforjava) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`2.31.55` -> `2.31.56` |
| [software.amazon.awssdk:aws-core](https://aws.amazon.com/sdkforjava) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`2.31.55` -> `2.31.56` |
| [software.amazon.awssdk:bom](https://aws.amazon.com/sdkforjava) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`2.31.55` -> `2.31.56` |
| [software.amazon.awssdk:auth](https://aws.amazon.com/sdkforjava) |
dependencies | misk/gradle/libs.versions.toml | gradle | patch |
`2.31.55` -> `2.31.56` |
| [com.amazonaws:aws-java-sdk-sqs](https://aws.amazon.com/sdkforjava)
([source](https://github.com/aws/aws-sdk-java)) | dependencies |
misk/gradle/libs.versions.toml | gradle | patch | `1.12.784` ->
`1.12.785` |
| [com.amazonaws:aws-java-sdk-s3](https://aws.amazon.com/sdkforjava)
([source](https://github.com/aws/aws-sdk-java)) | dependencies |
misk/gradle/libs.versions.toml | gradle | patch | `1.12.784` ->
`1.12.785` |
|
[com.amazonaws:aws-java-sdk-dynamodb](https://aws.amazon.com/sdkforjava)
([source](https://github.com/aws/aws-sdk-java)) | dependencies |
misk/gradle/libs.versions.toml | gradle | patch | `1.12.784` ->
`1.12.785` |
| [com.amazonaws:aws-java-sdk-core](https://aws.amazon.com/sdkforjava)
([source](https://github.com/aws/aws-sdk-java)) | dependencies |
misk/gradle/libs.versions.toml | gradle | patch | `1.12.784` ->
`1.12.785` |

---

### Release Notes

<details>
<summary>redis/lettuce (io.lettuce:lettuce-core)</summary>

###
[`v6.7.1.RELEASE`](https://github.com/redis/lettuce/releases/tag/6.7.1.RELEASE)

[Compare
Source](https://github.com/redis/lettuce/compare/6.7.0.RELEASE...6.7.1.RELEASE)

The Lettuce team is pleased to announce the Lettuce 6.7.1 service
release!
This release ships with bugfixes and dependency upgrades.

Lettuce 6 supports Redis 2.6+ up to Redis 7.x. In terms of Java runtime,
Lettuce requires
at least Java 8 and works with Java 21.

Thanks to all contributors who made Lettuce 6.7.1 possible.

### :green_book: Links

- Reference documentation:
https://lettuce.io/core/6.7.1.RELEASE/reference/
-   Javadoc: https://lettuce.io/core/6.7.1.RELEASE/api/

#### :lady_beetle: Bug Fixes

- NoClassDefFoundError in Lettuce 6.7.0
[#&#8203;3317](https://github.com/redis/lettuce/issues/3317) by
[@&#8203;tishun](https://github.com/tishun) in
https://github.com/redis/lettuce/pull/3319

**Full Changelog**:
https://github.com/redis/lettuce/compare/6.5.3.RELEASE...6.5.4.RELEASE

</details>

<details>
<summary>aws/aws-sdk-java (com.amazonaws:aws-java-sdk-sqs)</summary>

###
[`v1.12.785`](https://github.com/aws/aws-sdk-java/compare/1.12.784...1.12.785)

[Compare
Source](https://github.com/aws/aws-sdk-java/compare/1.12.784...1.12.785)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 6pm every weekday,before 2am
every weekday" in timezone Australia/Melbourne, Automerge - At any time
(no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Never, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://github.com/renovatebot/renovate).

GitOrigin-RevId: 3ce0964ca276b27fb68ea0abde9205dad8b8cec2