Improve handling of required query parameters ## Description
Currently if a request does not populate a required (non-nullable /
non-default) query parameter, misk will try to set a null value into the
parameter and cause an exception like:
```
java.lang.NullPointerException: Parameter specified as non-null is null: method <name>, parameter <name>
```

This change allows us to continue returning null to any
nullable/defaulted parameters, while throwing bad request if a required
query param is not passed.

## Testing Strategy

Confirmed the issue via tests. added additional unit tests to cover the
not present and default param cases

## Related Work
- Link any relevant PRs, tickets, or documentation for additional
context

## Communication Plan
  - was discussed with @adrw in #misk-external slack channel

should be no material impact, previous behaviour was an internal service
exception, will now be a bad request

## Definition of Done

Misk based services should now return HTTP 400 when a required param is
not provided rather than HTTP 500

## Rollout Strategy and Risk Mitigation
Monitor any endpoints currently throwing HTTP 500 due to missing
required query params and confirm those requests return HTTP 400

No mitigation required, behaviour should be unchanged other than a
different exception type

## Checklist
- [X] I have reviewed this PR with relevant experts and/or impacted
teams.
- [X] I have added tests to have confidence my changes work as expected.
- [X] I have a rollout plan that minimizes risks and includes monitoring
for potential issues.

Thank you for contributing to Misk! 🎉

[CLOSES cashapp/misk/pull/3403]

GitOrigin-RevId: 0f13740ef5bc56ffe7b05c3e9c1a27e2e6174978